source 'https://rubygems.org'

# Specify your gem's dependencies in my_lib.gemspec
gemspec
gem 'redditkit', '~> 1.0.1'
gem 'ruby-carrot'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'bson_ext'
gem 'pry'